---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: registry.access.redhat.com/rhel7:latest
    volumes:
     - /etc/pki/consumer:/etc/pki/consumer:ro
     - /etc/pki/entitlement:/etc/pki/entitlement:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
